name: G-Rise
version: '${project.version}'
main: com.gexel.grise.GRisePlugin
api-version: '1.21'
description: A vertical parkour minigame powered by the Mace and Wind Burst enchantment.
author: _gengis
website: https://github.com/gegecam30/G-rise

softdepend:
  - PlaceholderAPI

commands:
  gr:
    description: Main command for G-Rise plugin.
    usage: /<command> <subcommand> [args]
    aliases: [grise]
    permission: grise.use

permissions:
  grise.use:
    description: Allows basic use of the G-Rise minigame.
    default: true

  grise.admin:
    description: Allows access to all administrative G-Rise commands.
    default: op

  grise.bypass:
    description: Allows bypassing arena restrictions.
    default: op
